#!/usr/bin/env python3
# calc_daltons.py

'''Average weight of a protein sequence
'''

def main():
    '''Calculate average weight of protein sequence given length of sequence and
       average weight of amino acids
    '''
    pro_seq = '''MADPAAGPPPSEGEESTVRFARKGALRQKNVHEVKNHKFTARFFKQPTFCSHCTDFIWGFGKQGFQCQVC
    CFVVHKRCHEFVTFSCPGADKGPASDDPRSKHKFKIHTYSSPTFCDHCGSLLYGLIHQGMKCDTCMMNVH
    KRCVMNVPSLCGTDHTERRGRIYIQAHIDREVLIVVVRDAKNLVPMDPNGLSDPYVKLKLIPDPKSESKQ
    KTKTIKCSLNPEWNETFRFQLKESDKDRRLSVEIWDWDLTSRNDFMGSLSFGISELQKAGVDGWFKLLSQ
    EEGEYFNVPVPPEGSEGNEELRQKFERAKIGQGTKAPEEKTANTISKFDNNGNRDRMKLTDFNFLMVLGK
    GSFGKVMLSERKGTDELYAVKILKKDVVIQDDDVECTMVEKRVLALPGKPPFLTQLHSCFQTMDRLYFVM
    EYVNGGDLMYHIQQVGRFKEPHAVFYAAEIAIGLFFLQSKGIIYRDLKLDNVMLDSEGHIKIADFGMCKE
    NIWDGVTTKTFCGTPDYIAPEIIAYQPYGKSVDWWAFGVLLYEMLAGQAPFEGEDEDELFQSIMEHNVAY
    PKSMSKEAVAICKGLMTKHPGKRLGCGPEGERDIKEHAFFRYIDWEKLERKEIQPPYKPKARDKRDTSNF
    DKEFTRQPVELTPTDKLFIMNLDQNEFAGFSYTNPEFVINV'''

    avg_aa_wt = 110

    pro_seq = pro_seq.replace('\r', '').replace('\n', '')

    pro_len = len(pro_seq)

    avg_wt = (pro_len * avg_aa_wt) / 1000

    print(f'The length of "Protein kinase C beta type" is: {pro_len}')

    print(f'The average weight of this protein sequence in kilodaltons is: {avg_wt}')


if __name__ == '__main__':
    main()
